# Monitor Makefile
# Name&Surname: Metin Kagit
# Student_No: 1821221033
# Mail: metin.kagit@stu.fsm.edu.tr
# Lecture: Operating Systems - Project1

CC = gcc
CFLAGS = -Wall -Werror

all: program

program: monitor.c
	$(CC) $(CFLAGS) -o program monitor.c

clean:
	rm -f program  s    