# Multiplier Makefile
# Name&Surname: Metin Kagit
# Student_No: 1821221033
# Mail: metin.kagit@stu.fsm.edu.tr
# Lecture: Operating Systems - Project2

CC = gcc
CFLAGS = -Wall -Werror

all: program

program: multiplier.c
	$(CC) $(CFLAGS) -o program multiplier.c

clean:
	rm -f program