# Makefile
# Name&Surname: Metin Kagit
# Student_No: 1821221033
# Mail: metin.kagit@stu.fsm.edu.tr
# Lecture: Operating Systems - Project1

CC = gcc
CFLAGS = -Wall -Werror

all: adder subtractor multiplier divider trmn

adder: adder.c
	$(CC) $(CFLAGS) -o adder adder.c

subtractor: subtractor.c
	$(CC) $(CFLAGS) -o subtractor subtractor.c

multiplier: multiplier.c
	$(CC) $(CFLAGS) -o multiplier multiplier.c

divider: divider.c
	$(CC) $(CFLAGS) -o divider divider.c

trmn: trmn.c
	$(CC) $(CFLAGS) -o trmn trmn.c

clean:
	rm -f adder subtractor multiplier divider trmn